// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {service} from '../models';
import {upstream} from '../models';
import {global} from '../models';
import {backup} from '../models';

export function AddUpstreamModels(arg1:string,arg2:Array<plugin.Model>):Promise<number>;

export function ApplyModels(arg1:service.ApplyModelsRequest):Promise<service.ApplyModelsResult>;

export function ClearBackups(arg1:string):Promise<number>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteUpstream(arg1:string):Promise<void>;

export function DiscoverUpstreams():Promise<Array<upstream.Upstream>>;

export function ExportExamplePlugin():Promise<string>;

export function FetchModels(arg1:string,arg2:string,arg3:string):Promise<Array<plugin.RemoteModel>>;

export function GetALLLang():Promise<Array<global.LanguageInfo>>;

export function GetCurrentLang():Promise<string>;

export function GetLangPack():Promise<global.LanguagePack>;

export function GetLangTextMap():Promise<Record<string, string>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogLevel():Promise<string>;

export function GetPluginDir():Promise<string>;

export function GetProcessName():Promise<string>;

export function GetSettings():Promise<service.Settings>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function ImportUpstreams(arg1:service.ImportRequest):Promise<service.ImportResult>;

export function ListBackups(arg1:string):Promise<Array<backup.Entry>>;

export function ListPlugins():Promise<Array<service.PluginView>>;

export function ListUpstreams():Promise<Array<upstream.Upstream>>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenBackupDir(arg1:string):Promise<boolean>;

export function OpenFileSelect():Promise<string>;

export function OpenFolderSelect():Promise<string>;

export function OpenPluginDir():Promise<boolean>;

export function ProbeAll():Promise<Record<string, plugin.ProbeResult>>;

export function ProbeModel(arg1:string,arg2:string):Promise<plugin.ProbeResult>;

export function ProbeModels(arg1:string,arg2:Array<string>):Promise<Record<string, plugin.ProbeResult>>;

export function ProbeRemote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<plugin.ProbeResult>;

export function ProbeUpstream(arg1:string,arg2:string):Promise<Record<string, plugin.ProbeResult>>;

export function PullAllModels():Promise<Array<plugin.Model>>;

export function PullModels(arg1:string):Promise<Array<plugin.Model>>;

export function ReadBackup(arg1:string,arg2:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReloadPlugins():Promise<Array<service.PluginView>>;

export function RemoveUpstreamModel(arg1:string,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RevealPath(arg1:string):Promise<boolean>;

export function SaveModel(arg1:string,arg2:plugin.Model):Promise<plugin.Model>;

export function SaveUpstream(arg1:upstream.Upstream):Promise<upstream.Upstream>;

export function SetLanguage(arg1:string):Promise<boolean>;

export function SetLogLevel(arg1:string):Promise<boolean>;

export function SetModelEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<boolean>;

export function SetSourcePath(arg1:string,arg2:string):Promise<boolean>;

export function UpdateSettings(arg1:service.Settings):Promise<boolean>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
