// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUpstreamModels(arg1, arg2) {
  return window['go']['service']['App']['AddUpstreamModels'](arg1, arg2);
}

export function ApplyModels(arg1) {
  return window['go']['service']['App']['ApplyModels'](arg1);
}

export function ClearBackups(arg1) {
  return window['go']['service']['App']['ClearBackups'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['service']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteUpstream(arg1) {
  return window['go']['service']['App']['DeleteUpstream'](arg1);
}

export function DiscoverUpstreams() {
  return window['go']['service']['App']['DiscoverUpstreams']();
}

export function ExportExamplePlugin() {
  return window['go']['service']['App']['ExportExamplePlugin']();
}

export function FetchModels(arg1, arg2, arg3) {
  return window['go']['service']['App']['FetchModels'](arg1, arg2, arg3);
}

export function GetALLLang() {
  return window['go']['service']['App']['GetALLLang']();
}

export function GetCurrentLang() {
  return window['go']['service']['App']['GetCurrentLang']();
}

export function GetLangPack() {
  return window['go']['service']['App']['GetLangPack']();
}

export function GetLangTextMap() {
  return window['go']['service']['App']['GetLangTextMap']();
}

export function GetLogFileContent(arg1) {
  return window['go']['service']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['service']['App']['GetLogFiles']();
}

export function GetLogLevel() {
  return window['go']['service']['App']['GetLogLevel']();
}

export function GetPluginDir() {
  return window['go']['service']['App']['GetPluginDir']();
}

export function GetProcessName() {
  return window['go']['service']['App']['GetProcessName']();
}

export function GetSettings() {
  return window['go']['service']['App']['GetSettings']();
}

export function GetSystemInfo() {
  return window['go']['service']['App']['GetSystemInfo']();
}

export function ImportUpstreams(arg1) {
  return window['go']['service']['App']['ImportUpstreams'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['service']['App']['ListBackups'](arg1);
}

export function ListPlugins() {
  return window['go']['service']['App']['ListPlugins']();
}

export function ListUpstreams() {
  return window['go']['service']['App']['ListUpstreams']();
}

export function Notify(arg1, arg2) {
  return window['go']['service']['App']['Notify'](arg1, arg2);
}

export function OpenBackupDir(arg1) {
  return window['go']['service']['App']['OpenBackupDir'](arg1);
}

export function OpenFileSelect() {
  return window['go']['service']['App']['OpenFileSelect']();
}

export function OpenFolderSelect() {
  return window['go']['service']['App']['OpenFolderSelect']();
}

export function OpenPluginDir() {
  return window['go']['service']['App']['OpenPluginDir']();
}

export function ProbeAll() {
  return window['go']['service']['App']['ProbeAll']();
}

export function ProbeModel(arg1, arg2) {
  return window['go']['service']['App']['ProbeModel'](arg1, arg2);
}

export function ProbeModels(arg1, arg2) {
  return window['go']['service']['App']['ProbeModels'](arg1, arg2);
}

export function ProbeRemote(arg1, arg2, arg3, arg4) {
  return window['go']['service']['App']['ProbeRemote'](arg1, arg2, arg3, arg4);
}

export function ProbeUpstream(arg1, arg2) {
  return window['go']['service']['App']['ProbeUpstream'](arg1, arg2);
}

export function PullAllModels() {
  return window['go']['service']['App']['PullAllModels']();
}

export function PullModels(arg1) {
  return window['go']['service']['App']['PullModels'](arg1);
}

export function ReadBackup(arg1, arg2) {
  return window['go']['service']['App']['ReadBackup'](arg1, arg2);
}

export function ReadFileContent(arg1) {
  return window['go']['service']['App']['ReadFileContent'](arg1);
}

export function ReloadPlugins() {
  return window['go']['service']['App']['ReloadPlugins']();
}

export function RemoveUpstreamModel(arg1, arg2) {
  return window['go']['service']['App']['RemoveUpstreamModel'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['service']['App']['RestoreBackup'](arg1, arg2);
}

export function RevealPath(arg1) {
  return window['go']['service']['App']['RevealPath'](arg1);
}

export function SaveModel(arg1, arg2) {
  return window['go']['service']['App']['SaveModel'](arg1, arg2);
}

export function SaveUpstream(arg1) {
  return window['go']['service']['App']['SaveUpstream'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['service']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['service']['App']['SetLogLevel'](arg1);
}

export function SetModelEnabled(arg1, arg2, arg3) {
  return window['go']['service']['App']['SetModelEnabled'](arg1, arg2, arg3);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['service']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetSourcePath(arg1, arg2) {
  return window['go']['service']['App']['SetSourcePath'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['service']['App']['UpdateSettings'](arg1);
}

export function WindowClose() {
  return window['go']['service']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['service']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['service']['App']['WindowToggleMaximise']();
}
